# Generated by Django 2.2.15 on 2020-08-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineorder', '0002_auto_20200817_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'permissions': (('can_mark_released', 'Set order as released'), ('can_mark_closed', 'Set order as closed'), ('can_mark_cancelled', 'Set order as cancelled'))},
        ),
    ]
