# Generated by Django 2.2.15 on 2020-08-20 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineorder', '0003_auto_20200817_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='contact_person_and_no',
            field=models.CharField(default='', max_length=50, verbose_name='PM/CONTACT PERSON Name & HP No'),
        ),
       migrations.AddField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.date.today,blank=True,null=True,verbose_name='Expected Delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_code',
            field=models.CharField(default='', max_length=30, verbose_name='JOE PANEL PRODUCT CODE'),
        ),
        migrations.AddField(
            model_name='order',
            name='length',
            field=models.FloatField(default=0.0, verbose_name='Length (mm)'),
        ),
        migrations.AddField(
            model_name='order',
            name='po_ref_no',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False, verbose_name='PO REF No'),
        ),
        migrations.AddField(
            model_name='order',
            name='project_name',
            field=models.CharField(default='', max_length=50, verbose_name='PROJECT NAME'),
        ),
        migrations.AddField(
            model_name='order',
            name='project_site_address',
            field=models.CharField(default='', max_length=50, verbose_name='PROJECT SITE ADDRESS'),
        ),
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='QTY'),
        ),
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='order',
            name='unloading_method',
            field=models.CharField(choices=[('A', 'By Site Crane'), ('B', 'By Site Forklift'), ('C', 'By Lorry Crane: Separate arrangement & charges involved')], default='A', max_length=1, verbose_name='UNLOADING METHOD'),
        ),
        migrations.AddField(
            model_name='order',
            name='uom',
            field=models.CharField(default='', max_length=10, verbose_name='UOM (Unit of Measurement)'),
        ),
       migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date.today, verbose_name='DATE',blank=True,null=True),
        ),
    ]
