# Generated by Django 2.2.15 on 2020-08-20 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineorder', '0005_auto_20200820_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_code',
            new_name='joe_panel_product_code',
        ),
    ]
