# Generated by Django 2.2.15 on 2020-08-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineorder', '0006_auto_20200820_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
