# Generated by Django 2.2.15 on 2020-08-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineorder', '0007_auto_20200820_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unloading_method',
            field=models.CharField(choices=[('A', 'By Site Crane'), ('B', 'By Site Forklift'), ('C', 'By Lorry Crane: Separate arrangement & charges involved')], default='', max_length=1, verbose_name='UNLOADING METHOD'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uom',
            field=models.CharField(choices=[('1', 'CAN'), ('2', 'BAG'), ('3', 'ROLL/BOX'), ('4', 'BOX'), ('5', 'PAIL'), ('6', 'BOTTLE'), ('7', 'UNIT'), ('8', 'PCS'), ('9', 'SET')], default='', max_length=1, verbose_name='UOM (Unit of Measurement)'),
        ),
    ]
