# Generated by Django 2.2.15 on 2020-08-25 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineorder', '0010_auto_20200821_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='CONTRACTOR'),
        ),
    ]
